title: Introduction to Deep Learning
logo: /assets/img/logo.gif
description: Tuesday, August 9 & Wednesday, August 10, 2022  |  1:00 PM - 4:00 PM PDT
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
